.github/workflows/release.yaml

Reverts BobTheBuidler/ypricemagic#11

Revert "fix: correct automatic versioning"

---

y/contracts.py

Fix contract

---

y/contracts.py
y/prices/chainlink.py
y/prices/dex/balancer/v1.py
y/prices/dex/balancer/v2.py
y/prices/dex/uniswap/v2.py
y/prices/dex/uniswap/v3.py
y/prices/stable_swap/curve.py
y/time.py
y/utils/client.py
y/utils/multicall.py

get_block_timestamp
closest_block_after_timestamp
contract_creation_block
get_ethereum_client

feat: New async utils

---

tests/prices/test_chainlink.py
tests/prices/test_synthetix.py
y/prices/synthetix.py
y/time.py

* fix: test_synthetix with recent updates
* fix(test): fix test_chainlink for recent async changes
* fix: sync/async mismatch

Unblock event loop (#172)

---

y/prices/band.py
y/prices/magic.py
y/prices/utils/buckets.py

For early fantom blocks, neither chainlink nor onchain liquidity will work for a select few tokens. We will use band as a fallback in these cases.

feat: use band as fallback on fantom

---

y/prices/dex/balancer/v2.py

causes problems only when MULTICALL_PROCESSES env is set > 1

fix: pickling AttributeError edge case

---

y/ENVIRONMENT_VARIABLES.py
y/prices/yearn.py
y/utils/events.py

feat: YPRICEMAGIC_GETLOGS_DOP env

---

y/prices/dex/velodrome.py

fix: velo again (sorry)

---

y/prices/dex/uniswap/v2.py

This was not giving incorrect results but was making uni v2 module slower than necessary

fix: missing block kwarg

---

y/prices/dex/solidly.py
y/prices/dex/uniswap/v2.py
y/prices/dex/velodrome.py
y/utils/multicall.py

the cache was goofy and was being fetched for each price call. fixed now

fix: token1 cache

---

y/prices/dex/uniswap/v1.py
y/prices/dex/uniswap/v2.py
y/prices/dex/uniswap/v3.py
y/prices/stable_swap/curve.py

on longer running scripts, the current cache ttls are insufficient. The cached values are very small so I'm just bumping the ttl.

chore: bump cache ttls

---

y/prices/dex/uniswap/v3.py

uniswap v3 giving erroneous price for LQTY, must investigate

fix: temp fix LQTY

---

y/_db/utils/utils.py
y/time.py

less issues w provider rate limits

feat: disk cache block timestamp for better use with commercial rpcs

---

y/_db/__init__.py
y/_db/config.py
y/_db/exceptions.py
y/_db/utils/__init__.py

When a new ydb schema is released, ypm will prompt the user to delete their local db and ask if they want ypm to take care of it

feat: click prompt to delete ydb

---

y/_db/utils/utils.py

fix: select statement

---

y/_db/utils/contract.py
y/_db/utils/price.py
y/_db/utils/token.py
y/_db/utils/utils.py
y/classes/common.py
y/contracts.py
y/prices/magic.py
y/prices/utils/buckets.py
y/time.py

feat: dont wait for db inserts

---

y/contracts.py

sometimes one of these calls would revert and not be properly caught. now it is

fix: has_method and has_methods with ContractLogicError

---

requirements.txt
y/_db/common.py
y/prices/dex/uniswap/v3.py

Events.events now returns an ASyncIterator so it will work as an iterator as well as an aiterator

feat: iterable events

---

y/prices/dex/balancer/v2.py
y/prices/dex/uniswap/v3.py

make some pvt methods public so they show in docs

chore: refactor private to public

---

y/prices/dex/uniswap/v2.py

makes batch calls run out of gas :(

feat: disable uniswap helper mainnet

---

y/prices/yearn.py

previously, if a vault token's underlying couldn't be priced, a PriceError was immediately raised. 
Now, it will fallback to dexes if there is any liquidity available. otherwise it will then raise PriceError.

fix: yearn fallback to dex when underlying cant get price

---

y/prices/one_to_one.py

mapping these manually until I have a chance to build code to algorithmically fetch all gauges

feat: support sdai-usdm and yfimkusd gauges

---

y/utils/raw_calls.py

fixes edge case with unhandled exception on some shitcoins

fix: raw_calls._totalSupply

---

y/contracts.py

fixes edge case with unhandled revert string

fix: has_method

---

tests/prices/lending/test_compound.py
tests/prices/test_magic.py
tests/prices/utils/test_buckets.py
y/_db/utils/token.py
y/contracts.py
y/convert.py
y/prices/chainlink.py
y/prices/dex/mooniswap.py
y/prices/dex/uniswap/uniswap.py
y/prices/dex/uniswap/v2.py
y/prices/eth_derivs/creth.py
y/prices/lending/aave.py
y/prices/lending/ib.py
y/prices/magic.py
y/prices/popsicle.py
y/prices/stable_swap/belt.py
y/prices/stable_swap/curve.py
y/prices/stable_swap/mstablefeederpool.py
y/prices/stable_swap/saddle.py
y/prices/synthetix.py
y/prices/tokenized_fund/gelato.py
y/prices/utils/buckets.py
y/utils/multicall.py
y/utils/raw_calls.py

Handle checksums in a subthread where possible to keep the event loop unblocked

feat: async checksum

---

requirements.txt
y/convert.py

cache any checksums that are computed in this code

feat: monkey patch dank_mids's patch of brownie's decoders

---

y/_db/common.py
y/prices/dex/uniswap/v2.py

feat: use single-use log filter for uniswap v2 pool loading

---

y/prices/dex/uniswap/v2.py

fix: quickfix for Invalid Request in uniswap helper contract

---

y/_db/common.py
y/_db/decorators.py
y/_db/utils/contract.py
y/_db/utils/logs.py
y/_db/utils/price.py
y/_db/utils/token.py
y/_db/utils/utils.py
y/constants.py
y/contracts.py
y/networks.py
y/prices/band.py
y/prices/chainlink.py
y/prices/dex/balancer/balancer.py
y/prices/dex/balancer/v2.py
y/prices/dex/uniswap/v2.py
y/prices/dex/uniswap/v3.py
y/prices/eth_derivs/creth.py
y/prices/eth_derivs/wsteth.py
y/prices/rkp3r.py
y/prices/solidex.py
y/prices/stable_swap/curve.py
y/prices/stable_swap/froyo.py
y/prices/stable_swap/saddle.py
y/prices/synthetix.py
y/prices/utils/sense_check.py
y/prices/utils/ypriceapi.py
y/prices/yearn.py
y/time.py

will mostly impact loads from db, but other stuff is nice too

feat: use CHAINID constant throughout repo

---

y/_db/utils/logs.py
y/contracts.py
y/prices/dex/uniswap/uniswap.py
y/prices/dex/uniswap/v3.py
y/prices/lending/aave.py
y/prices/magic.py
y/prices/stable_swap/curve.py
y/utils/events.py
y/utils/gather.py
y/utils/multicall.py

feat: implement igather

---

y/prices/gearbox.py
y/prices/lending/aave.py
y/prices/pendle.py
y/prices/synthetix.py
y/prices/tokenized_fund/tokensets.py
y/utils/__init__.py
y/utils/gather.py

This reverts commit a220c598e5fa898ff4b5e04df0cd8bd821e8930d.

Revert "feat: gather2 (#922)"

---

y/prices/dex/uniswap/v3.py

also rip out deprecated `__contains_cache__` to conserve RAM

feat: optimize UniswapV3.pools_for_token

---

y/utils/raw_calls.py

hexbytes v1 had a breaking change, this PR makes ypricemagic compatible with both versions

fix: raw_call with address output on hexbytes>=1

---

requirements.txt

This is in preparation for a future release and will allow me to test the release in prod

chore: loosen brownie pin

---

y/prices/dex/uniswap/uniswap.py
y/prices/dex/uniswap/v2.py
y/prices/dex/uniswap/v3.py

we put these here a long time ago to ensure the event loop didnt get too clogged. in the meantime, I've made a lot of optimizations across all parts of the stack which make this less of an issue and allow me to safely increase the concurrency.

feat: loosen uniswap semaphores

---

y/prices/dex/uniswap/v3.py

This is a quickfix for trillion dollar prices that happen sometimes. I might still need to actually debug the root cause, time will tell.

fix: add lazy sense check to uniswap v3 module
